// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK2sE9K508lGnGm6Tz79l_rySzlmQq9RU',
    appId: '1:220073582903:web:75250b1241e923f5d47ab2',
    messagingSenderId: '220073582903',
    projectId: 'vocaboost-fb',
    authDomain: 'vocaboost-fb.firebaseapp.com',
    storageBucket: 'vocaboost-fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMbIr5ZTMMsRWO9MVQ9b9sV-r2gF7fIM',
    appId: '1:220073582903:android:5d62ef46528e3d48d47ab2',
    messagingSenderId: '220073582903',
    projectId: 'vocaboost-fb',
    storageBucket: 'vocaboost-fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC2U1TgTbGTmWSjSj0Tf8PqXCUdGMNbus',
    appId: '1:220073582903:ios:4595810eee1f9f21d47ab2',
    messagingSenderId: '220073582903',
    projectId: 'vocaboost-fb',
    storageBucket: 'vocaboost-fb.firebasestorage.app',
    iosBundleId: 'com.example.vocaboost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC2U1TgTbGTmWSjSj0Tf8PqXCUdGMNbus',
    appId: '1:220073582903:ios:4595810eee1f9f21d47ab2',
    messagingSenderId: '220073582903',
    projectId: 'vocaboost-fb',
    storageBucket: 'vocaboost-fb.firebasestorage.app',
    iosBundleId: 'com.example.vocaboost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK2sE9K508lGnGm6Tz79l_rySzlmQq9RU',
    appId: '1:220073582903:web:56ceca8edc761088d47ab2',
    messagingSenderId: '220073582903',
    projectId: 'vocaboost-fb',
    authDomain: 'vocaboost-fb.firebaseapp.com',
    storageBucket: 'vocaboost-fb.firebasestorage.app',
  );
}
